name: Stable Release Build (Galaxy A50)

on:
  workflow_dispatch:
  push:
    branches:
      - "android-*"

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        type: [aosp-12-e, aosp-11-e, recovery-12-p]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y

      - name: Build Mint kernel
        run: |
          set -eo pipefail
          VARIANT=$(echo ${{ matrix.type }} | cut -d '-' -f1)
          ANDROID=$(echo ${{ matrix.type }} | cut -d '-' -f2)
          SELINUX=$(echo ${{ matrix.type }} | cut -d '-' -f3)
          
          ./build.sh --automated --device a50 --variant $VARIANT --android $ANDROID -$SELINUX --kernelsu

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mint-kernel-${{ matrix.type }}
          path: |
            out/Mint-*.zip
            out/Image
          if-no-files-found: error