name: Stable Release Build (Galaxy A50)

on:
  workflow_dispatch:
  push:
    branches:
      - "android-*"

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        type: [aosp-12-e]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y

      - name: Build Mint kernel
        run: |
          set -eo pipefail
          VARIANT=$(echo ${{ matrix.type }} | cut -d '-' -f1)
          ANDROID=$(echo ${{ matrix.type }} | cut -d '-' -f2)
          SELINUX=$(echo ${{ matrix.type }} | cut -d '-' -f3)
          ./build.sh --automated --device a50 --variant $VARIANT --android $ANDROID -$SELINUX --kernelsu

      - name: Upload Kernel Zip
        uses: actions/upload-artifact@v4
        with:
          name: kernel-release
          path: out/Mint-*.zip
          if-no-files-found: error

  # release:
    # name: Create GitHub Release
    # if: ${{ !contains(github.event.head_commit.message, '[skip rel]') }}
    # needs: build
    # runs-on: ubuntu-latest
    # permissions:
      # contents: write
    # steps:
      # - uses: actions/checkout@v4

      # - name: Download Artifact
        # uses: actions/download-artifact@v4
        # with:
          # name: kernel-release
          # path: ./release

      # - name: Upload release
        # uses: softprops/action-gh-release@v1
        # with:
          # tag_name: mainline-${{ github.run_number }}_a50dx
          # name: "Mint Stable (Build ${{ github.run_number }})"
          # prerelease: true
          # body_path: "./tools/make/release/a50-release.md"
          # files: ./release/*.zip
        # env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}